export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";

export const PRODUCT_ITEMDETAILS_REQUEST = "PRODUCT_ITEMDETAILS_REQUEST";
export const PRODUCT_ITEMDETAILS_SUCCESS = "PRODUCT_ITEMDETAILS_SUCCESS";
export const PRODUCT_ITEMDETAILS_FAILS = "PRODUCT_ITEMDETAILS_FAILS";

export const POST_REVIEW_REQUEST = "POST_REVIEW_REQUEST";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

// by admin
export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAIL = "ADD_NEW_PRODUCT_FAIL";

export const POST_PRODUCT_BY_ID_REQUEST = "POST_PRODUCT_BY_ID_REQUEST";
export const POST_PRODUCT_BY_ID_SUCCESS = "POST_PRODUCT_BY_ID_SUCCESS";
export const POST_PRODUCT_BY_ID_FAIL = "POST_PRODUCT_BY_ID_FAIL";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const EDIT_PRODUCT_BY_ID_REQUEST = "EDIT_PRODUCT_BY_ID_REQUEST";
export const EDIT_PRODUCT_BY_ID_SUCCESS = "EDIT_PRODUCT_BY_ID_SUCCESS";
export const EDIT_PRODUCT_BY_ID_FAIL = "EDIT_PRODUCT_BY_ID_FAIL";
